<a href="https://colab.research.google.com/github/beansugar/v2ray/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,4,5])#列表转换
print(a)
print(a.size)#side 取得数量

[1 2 4 5]
4


多维阵列

In [ ]:
import numpy as np
data=np.array([[2,2],
               [2,3]])#2*2的阵列
print(data)
data=np.empty([2,4,5])#2*4*5的阵列
print(data)
data=np.ones([2,4,5])#阵列内容全是1
print(data)
data=np.arange(10)#内容0到9
print(data)

逐元运算

In [ ]:
import numpy as np
data1=np.array([1,10,15])
data2=np.array([2,5,10])
result=data1+data2  #加法运算
print("加法",result)
result=data1-data2  #减法运算
print("减法:",result)
#除了加减乘除还可以做比较
result=data1<data2
print("小于:",result

矩阵运算

In [ ]:
import numpy as np
data1=np.array([[1,3,5]])#1*3
data2=np.array([[2,5,4],
                [3,5,5],
                [3,4,6]])#3*3
#result=data1@data2 #内积
result=data1.dot(data2)
print(result)
result=np.outer(data1,data2)#外积
print(result)

[[26 40 49]]
[[ 2  5  4  3  5  5  3  4  6]
 [ 6 15 12  9 15 15  9 12 18]
 [10 25 20 15 25 25 15 20 30]]


统计运算

In [ ]:
import numpy as np
data=np.array([[1,5],
              [2,5],
              [1,7],
              [5,9]])#4*2矩阵
result=data.sum()
print(result)#求和
result=data.min(axis=0)#针对行最小值
print(result)
result=data.mean(axis=1)#针对列平均值
print(result)
result=data.std()#标准差
print(result)
result=data.cumsum(axis=1)#针对行逐行累加
print(result)

axis=1针对行
axis=0针对列

In [ ]:
import numpy as np 
data=np.array([[10,4],
               [6,5],
               [1,3]])
print(data.shape)#阵列形状
print(data.T) #资料转置
data1=data.ravel()#资料的扁平化
print(data1)
data2=data.reshape(2,3)#资料重塑形状
print(data2)
new=np.ones(15).reshape(3,5)
n
print(new1)

In [ ]:

#练习
import numpy as np
data1=np.arange(10).reshape(2,5)
data2=np.ones(10).reshape(2,5)
result=data1+data2
print(result)
new=result*data1
print(new)

索引 Indexing
切片 slicing

In [ ]:
import numpy as np
data=np.array([1,5,6,7])#单唯独索引
print(data[0])
print(data[3])

In [ ]:
import numpy as np 
data=np.array([
               [1,10,5],
               [3,5,7]
                       ])
print(data[0,1]) #多唯独索引

In [ ]:
import numpy as np
data=np.array([1,4,5])#切片
print(data[0:1])
print(data[ :2])

data=np.array([
             [
          [1,10,10],[1,3,4]],
             [
          [1,5,10],[4,5,5]]
                        ])
print(data[0:2,0:2,0:2])
print(data[0:1,...])#...代表全都要

[1]
[1 4]
[[[ 1 10]
  [ 1  3]]

 [[ 1  5]
  [ 4  5]]]
[[[ 1 10 10]
  [ 1  3  4]]]
